# Generated by Django 4.2.9 on 2024-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_products', '0004_purchase_purchaseitem_purchase_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(related_name='cart_items', through='e_products.CartItem', to='e_products.product'),
        ),
    ]
