# Generated by Django 4.2.9 on 2024-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_products', '0005_alter_shoppingcart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(related_name='shopping_carts', through='e_products.CartItem', to='e_products.product'),
        ),
    ]
