# Generated by Django 4.2.9 on 2024-01-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0002_profile_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='marital_status',
        ),
    ]
